### ISSUE TITLE
没更新了吗？

### ISSUE THREAD

**Issue by iBotasky** [benhero/GLStudio#2]
如题

**Comment by iBotasky** [comment]
卡在矩阵了，迫切需要啊大兄弟

**Comment by iBotasky** [comment]
忘了说了，写的很好，之前的文章很多都看不懂，看到你的正交投影，一下就明白了

**Comment by benhero** [comment]
有更新的，不过最近公司办公网络有点问题，所以没处理。会继续更新，不过矩阵不是我接下来写下一个章节，下一章写相机的。要不你加下我微信沟通，我可以把之前看的矩阵资料发给你。微信号 : ***




| |
benhero
邮箱：benhero@126.com
|

Signature is customized by Netease Mail Master

在2019年03月22日 16:33，Botaksy 写道：

忘了说了，写的很好，之前的文章很多都看不懂，看到你的正交投影，一下就明白了
