### ISSUE TITLE
写的非常通俗易懂。是我看过的所有opengl es教程里面干货最多，最直接的。

### ISSUE THREAD

**Issue by Adolphsa** [benhero/GLStudio#4]
Android OpenGL ES 7.2多纹理绘制这一节里面讲了两种方法来进行多纹理绘制，第一种是多次绘制，单纹理单元。第二种是单次绘制，多纹理单元。我使用的是opengl es 3.0的版本，按照文章中的第二种绘制多纹理的方式来进行多纹理绘制，但是都只能显示出两张图片中的其中一张，能看看第二种绘制多纹理的完整代码吗

**Comment by benhero** [comment]
我安排时间看一下哈

**Comment by benhero** [comment]
已经添加了多纹理绘制的方式了，可以看下https://github.com/benhero/GLStudio/blob/master/app/src/main/java/com/benhero/glstudio/renderer/L6_2_2TextureRenderer.kt，之前在课程里是已经实现了，放在L6_3_TextureRenderer蒙版绘制的章节里，当时感觉会比较复杂，所以就没有写相应的课程，怕讲得比较深，多纹理单元的绘制确实会麻烦些。可以结合这两个章节学习探索下。另外，AndroidManifest里我没有升级到GL3.0，可以自行升级，暂时不影响当前工程的运行效果。

**Comment by benhero** [comment]
已经添加了多纹理绘制的方式了，可以看下https://github.com/benhero/GLStudio/blob/master/app/src/main/java/com/benhero/glstudio/renderer/L6_2_2TextureRenderer.kt 
 ，之前在课程里是已经实现了，放在L6_3_TextureRenderer蒙版绘制的章节里，当时感觉会比较复杂，所以就没有写相应的课程，怕讲得比较深，多纹理单元的绘制确实会麻烦些。可以结合这两个章节学习探索下。另外，AndroidManifest里我没有升级到GL3.0，可以自行升级，暂时不影响当前工程的运行效果。

**Comment by Adolphsa** [comment]
好的。谢谢。
